//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTaiKhoan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6MF64C4\\SQLEXPRESS;Initial Catalog=db_TaiKhoan;Integrated Sec" +
            "urity=True")]
        public string db_TaiKhoanConnectionString {
            get {
                return ((string)(this["db_TaiKhoanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6MF64C4\\SQLEXPRESS;Initial Catalog=ql_Users;Integrated Securi" +
            "ty=True")]
        public string ql_UsersConnectionString {
            get {
                return ((string)(this["ql_UsersConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6MF64C4\\SQLEXPRESS;Initial Catalog=db_HoaDon;Integrated Secur" +
            "ity=True")]
        public string db_HoaDonConnectionString {
            get {
                return ((string)(this["db_HoaDonConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6MF64C4\\SQLEXPRESS;Initial Catalog=db_QuanLyHoaDon;Integrated" +
            " Security=True")]
        public string db_QuanLyHoaDonConnectionString {
            get {
                return ((string)(this["db_QuanLyHoaDonConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-6MF64C4\\SQLEXPRESS;Initial Catalog=ql;Integrated Security=Tru" +
            "e")]
        public string qlConnectionString {
            get {
                return ((string)(this["qlConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=qlbanhangVQ.mssql.somee.com;Initial Catalog=qlbanhangVQ;Persist Secur" +
            "ity Info=True;User ID=vinhquy1402_SQLLogin_1;Password=p1yoxf6u2n")]
        public string qlbanhangVQConnectionString {
            get {
                return ((string)(this["qlbanhangVQConnectionString"]));
            }
        }
    }
}
