#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTaiKhoan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ql")]
	public partial class dbcsdlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin_AccessGroupUserForm(admin_AccessGroupUserForm instance);
    partial void Updateadmin_AccessGroupUserForm(admin_AccessGroupUserForm instance);
    partial void Deleteadmin_AccessGroupUserForm(admin_AccessGroupUserForm instance);
    partial void Insertadmin_AccessGroupUserModule(admin_AccessGroupUserModule instance);
    partial void Updateadmin_AccessGroupUserModule(admin_AccessGroupUserModule instance);
    partial void Deleteadmin_AccessGroupUserModule(admin_AccessGroupUserModule instance);
    partial void Insertadmin_AccessUserForm(admin_AccessUserForm instance);
    partial void Updateadmin_AccessUserForm(admin_AccessUserForm instance);
    partial void Deleteadmin_AccessUserForm(admin_AccessUserForm instance);
    partial void Insertadmin_Form(admin_Form instance);
    partial void Updateadmin_Form(admin_Form instance);
    partial void Deleteadmin_Form(admin_Form instance);
    partial void Insertadmin_GroupUser(admin_GroupUser instance);
    partial void Updateadmin_GroupUser(admin_GroupUser instance);
    partial void Deleteadmin_GroupUser(admin_GroupUser instance);
    partial void Insertadmin_Module(admin_Module instance);
    partial void Updateadmin_Module(admin_Module instance);
    partial void Deleteadmin_Module(admin_Module instance);
    partial void Insertadmin_User(admin_User instance);
    partial void Updateadmin_User(admin_User instance);
    partial void Deleteadmin_User(admin_User instance);
    partial void InserttbHoaDon(tbHoaDon instance);
    partial void UpdatetbHoaDon(tbHoaDon instance);
    partial void DeletetbHoaDon(tbHoaDon instance);
    partial void InserttbHoaDonChiTiet(tbHoaDonChiTiet instance);
    partial void UpdatetbHoaDonChiTiet(tbHoaDonChiTiet instance);
    partial void DeletetbHoaDonChiTiet(tbHoaDonChiTiet instance);
    partial void InserttbKho(tbKho instance);
    partial void UpdatetbKho(tbKho instance);
    partial void DeletetbKho(tbKho instance);
    partial void InserttbSanPham(tbSanPham instance);
    partial void UpdatetbSanPham(tbSanPham instance);
    partial void DeletetbSanPham(tbSanPham instance);
    partial void InserttbSanPhamChiTiet(tbSanPhamChiTiet instance);
    partial void UpdatetbSanPhamChiTiet(tbSanPhamChiTiet instance);
    partial void DeletetbSanPhamChiTiet(tbSanPhamChiTiet instance);
    #endregion
		
		public dbcsdlDataContext() : 
				base(global::QuanLyTaiKhoan.Properties.Settings.Default.qlConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin_AccessGroupUserForm> admin_AccessGroupUserForms
		{
			get
			{
				return this.GetTable<admin_AccessGroupUserForm>();
			}
		}
		
		public System.Data.Linq.Table<admin_AccessGroupUserModule> admin_AccessGroupUserModules
		{
			get
			{
				return this.GetTable<admin_AccessGroupUserModule>();
			}
		}
		
		public System.Data.Linq.Table<admin_AccessUserForm> admin_AccessUserForms
		{
			get
			{
				return this.GetTable<admin_AccessUserForm>();
			}
		}
		
		public System.Data.Linq.Table<admin_Form> admin_Forms
		{
			get
			{
				return this.GetTable<admin_Form>();
			}
		}
		
		public System.Data.Linq.Table<admin_GroupUser> admin_GroupUsers
		{
			get
			{
				return this.GetTable<admin_GroupUser>();
			}
		}
		
		public System.Data.Linq.Table<admin_Module> admin_Modules
		{
			get
			{
				return this.GetTable<admin_Module>();
			}
		}
		
		public System.Data.Linq.Table<admin_User> admin_Users
		{
			get
			{
				return this.GetTable<admin_User>();
			}
		}
		
		public System.Data.Linq.Table<tbHoaDon> tbHoaDons
		{
			get
			{
				return this.GetTable<tbHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tbHoaDonChiTiet> tbHoaDonChiTiets
		{
			get
			{
				return this.GetTable<tbHoaDonChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<tbKho> tbKhos
		{
			get
			{
				return this.GetTable<tbKho>();
			}
		}
		
		public System.Data.Linq.Table<tbSanPham> tbSanPhams
		{
			get
			{
				return this.GetTable<tbSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tbSanPhamChiTiet> tbSanPhamChiTiets
		{
			get
			{
				return this.GetTable<tbSanPhamChiTiet>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_AccessGroupUserForm")]
	public partial class admin_AccessGroupUserForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _guf_id;
		
		private System.Nullable<bool> _guf_active;
		
		private System.Nullable<int> _groupuser_id;
		
		private System.Nullable<int> _form_id;
		
		private EntityRef<admin_GroupUser> _admin_GroupUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onguf_idChanging(int value);
    partial void Onguf_idChanged();
    partial void Onguf_activeChanging(System.Nullable<bool> value);
    partial void Onguf_activeChanged();
    partial void Ongroupuser_idChanging(System.Nullable<int> value);
    partial void Ongroupuser_idChanged();
    partial void Onform_idChanging(System.Nullable<int> value);
    partial void Onform_idChanged();
    #endregion
		
		public admin_AccessGroupUserForm()
		{
			this._admin_GroupUser = default(EntityRef<admin_GroupUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guf_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int guf_id
		{
			get
			{
				return this._guf_id;
			}
			set
			{
				if ((this._guf_id != value))
				{
					this.Onguf_idChanging(value);
					this.SendPropertyChanging();
					this._guf_id = value;
					this.SendPropertyChanged("guf_id");
					this.Onguf_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guf_active", DbType="Bit")]
		public System.Nullable<bool> guf_active
		{
			get
			{
				return this._guf_active;
			}
			set
			{
				if ((this._guf_active != value))
				{
					this.Onguf_activeChanging(value);
					this.SendPropertyChanging();
					this._guf_active = value;
					this.SendPropertyChanged("guf_active");
					this.Onguf_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_id", DbType="Int")]
		public System.Nullable<int> groupuser_id
		{
			get
			{
				return this._groupuser_id;
			}
			set
			{
				if ((this._groupuser_id != value))
				{
					if (this._admin_GroupUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongroupuser_idChanging(value);
					this.SendPropertyChanging();
					this._groupuser_id = value;
					this.SendPropertyChanged("groupuser_id");
					this.Ongroupuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_id", DbType="Int")]
		public System.Nullable<int> form_id
		{
			get
			{
				return this._form_id;
			}
			set
			{
				if ((this._form_id != value))
				{
					this.Onform_idChanging(value);
					this.SendPropertyChanging();
					this._form_id = value;
					this.SendPropertyChanged("form_id");
					this.Onform_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_GroupUser_admin_AccessGroupUserForm", Storage="_admin_GroupUser", ThisKey="groupuser_id", OtherKey="groupuser_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public admin_GroupUser admin_GroupUser
		{
			get
			{
				return this._admin_GroupUser.Entity;
			}
			set
			{
				admin_GroupUser previousValue = this._admin_GroupUser.Entity;
				if (((previousValue != value) 
							|| (this._admin_GroupUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._admin_GroupUser.Entity = null;
						previousValue.admin_AccessGroupUserForms.Remove(this);
					}
					this._admin_GroupUser.Entity = value;
					if ((value != null))
					{
						value.admin_AccessGroupUserForms.Add(this);
						this._groupuser_id = value.groupuser_id;
					}
					else
					{
						this._groupuser_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("admin_GroupUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_AccessGroupUserModule")]
	public partial class admin_AccessGroupUserModule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gum_id;
		
		private System.Nullable<bool> _gum_active;
		
		private System.Nullable<int> _groupuser_id;
		
		private System.Nullable<int> _module_id;
		
		private EntityRef<admin_GroupUser> _admin_GroupUser;
		
		private EntityRef<admin_Module> _admin_Module;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongum_idChanging(int value);
    partial void Ongum_idChanged();
    partial void Ongum_activeChanging(System.Nullable<bool> value);
    partial void Ongum_activeChanged();
    partial void Ongroupuser_idChanging(System.Nullable<int> value);
    partial void Ongroupuser_idChanged();
    partial void Onmodule_idChanging(System.Nullable<int> value);
    partial void Onmodule_idChanged();
    #endregion
		
		public admin_AccessGroupUserModule()
		{
			this._admin_GroupUser = default(EntityRef<admin_GroupUser>);
			this._admin_Module = default(EntityRef<admin_Module>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gum_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int gum_id
		{
			get
			{
				return this._gum_id;
			}
			set
			{
				if ((this._gum_id != value))
				{
					this.Ongum_idChanging(value);
					this.SendPropertyChanging();
					this._gum_id = value;
					this.SendPropertyChanged("gum_id");
					this.Ongum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gum_active", DbType="Bit")]
		public System.Nullable<bool> gum_active
		{
			get
			{
				return this._gum_active;
			}
			set
			{
				if ((this._gum_active != value))
				{
					this.Ongum_activeChanging(value);
					this.SendPropertyChanging();
					this._gum_active = value;
					this.SendPropertyChanged("gum_active");
					this.Ongum_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_id", DbType="Int")]
		public System.Nullable<int> groupuser_id
		{
			get
			{
				return this._groupuser_id;
			}
			set
			{
				if ((this._groupuser_id != value))
				{
					if (this._admin_GroupUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongroupuser_idChanging(value);
					this.SendPropertyChanging();
					this._groupuser_id = value;
					this.SendPropertyChanged("groupuser_id");
					this.Ongroupuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_id", DbType="Int")]
		public System.Nullable<int> module_id
		{
			get
			{
				return this._module_id;
			}
			set
			{
				if ((this._module_id != value))
				{
					if (this._admin_Module.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmodule_idChanging(value);
					this.SendPropertyChanging();
					this._module_id = value;
					this.SendPropertyChanged("module_id");
					this.Onmodule_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_GroupUser_admin_AccessGroupUserModule", Storage="_admin_GroupUser", ThisKey="groupuser_id", OtherKey="groupuser_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public admin_GroupUser admin_GroupUser
		{
			get
			{
				return this._admin_GroupUser.Entity;
			}
			set
			{
				admin_GroupUser previousValue = this._admin_GroupUser.Entity;
				if (((previousValue != value) 
							|| (this._admin_GroupUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._admin_GroupUser.Entity = null;
						previousValue.admin_AccessGroupUserModules.Remove(this);
					}
					this._admin_GroupUser.Entity = value;
					if ((value != null))
					{
						value.admin_AccessGroupUserModules.Add(this);
						this._groupuser_id = value.groupuser_id;
					}
					else
					{
						this._groupuser_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("admin_GroupUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Module_admin_AccessGroupUserModule", Storage="_admin_Module", ThisKey="module_id", OtherKey="module_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public admin_Module admin_Module
		{
			get
			{
				return this._admin_Module.Entity;
			}
			set
			{
				admin_Module previousValue = this._admin_Module.Entity;
				if (((previousValue != value) 
							|| (this._admin_Module.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._admin_Module.Entity = null;
						previousValue.admin_AccessGroupUserModules.Remove(this);
					}
					this._admin_Module.Entity = value;
					if ((value != null))
					{
						value.admin_AccessGroupUserModules.Add(this);
						this._module_id = value.module_id;
					}
					else
					{
						this._module_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("admin_Module");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_AccessUserForm")]
	public partial class admin_AccessUserForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uf_id;
		
		private System.Nullable<bool> _uf_active;
		
		private System.Nullable<int> _username_id;
		
		private System.Nullable<int> _form_id;
		
		private EntityRef<admin_Form> _admin_Form;
		
		private EntityRef<admin_User> _admin_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuf_idChanging(int value);
    partial void Onuf_idChanged();
    partial void Onuf_activeChanging(System.Nullable<bool> value);
    partial void Onuf_activeChanged();
    partial void Onusername_idChanging(System.Nullable<int> value);
    partial void Onusername_idChanged();
    partial void Onform_idChanging(System.Nullable<int> value);
    partial void Onform_idChanged();
    #endregion
		
		public admin_AccessUserForm()
		{
			this._admin_Form = default(EntityRef<admin_Form>);
			this._admin_User = default(EntityRef<admin_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uf_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uf_id
		{
			get
			{
				return this._uf_id;
			}
			set
			{
				if ((this._uf_id != value))
				{
					this.Onuf_idChanging(value);
					this.SendPropertyChanging();
					this._uf_id = value;
					this.SendPropertyChanged("uf_id");
					this.Onuf_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uf_active", DbType="Bit")]
		public System.Nullable<bool> uf_active
		{
			get
			{
				return this._uf_active;
			}
			set
			{
				if ((this._uf_active != value))
				{
					this.Onuf_activeChanging(value);
					this.SendPropertyChanging();
					this._uf_active = value;
					this.SendPropertyChanged("uf_active");
					this.Onuf_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_id", DbType="Int")]
		public System.Nullable<int> username_id
		{
			get
			{
				return this._username_id;
			}
			set
			{
				if ((this._username_id != value))
				{
					if (this._admin_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusername_idChanging(value);
					this.SendPropertyChanging();
					this._username_id = value;
					this.SendPropertyChanged("username_id");
					this.Onusername_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_id", DbType="Int")]
		public System.Nullable<int> form_id
		{
			get
			{
				return this._form_id;
			}
			set
			{
				if ((this._form_id != value))
				{
					if (this._admin_Form.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onform_idChanging(value);
					this.SendPropertyChanging();
					this._form_id = value;
					this.SendPropertyChanged("form_id");
					this.Onform_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Form_admin_AccessUserForm", Storage="_admin_Form", ThisKey="form_id", OtherKey="form_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public admin_Form admin_Form
		{
			get
			{
				return this._admin_Form.Entity;
			}
			set
			{
				admin_Form previousValue = this._admin_Form.Entity;
				if (((previousValue != value) 
							|| (this._admin_Form.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._admin_Form.Entity = null;
						previousValue.admin_AccessUserForms.Remove(this);
					}
					this._admin_Form.Entity = value;
					if ((value != null))
					{
						value.admin_AccessUserForms.Add(this);
						this._form_id = value.form_id;
					}
					else
					{
						this._form_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("admin_Form");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_User_admin_AccessUserForm", Storage="_admin_User", ThisKey="username_id", OtherKey="username_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public admin_User admin_User
		{
			get
			{
				return this._admin_User.Entity;
			}
			set
			{
				admin_User previousValue = this._admin_User.Entity;
				if (((previousValue != value) 
							|| (this._admin_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._admin_User.Entity = null;
						previousValue.admin_AccessUserForms.Remove(this);
					}
					this._admin_User.Entity = value;
					if ((value != null))
					{
						value.admin_AccessUserForms.Add(this);
						this._username_id = value.username_id;
					}
					else
					{
						this._username_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("admin_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_Form")]
	public partial class admin_Form : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _form_id;
		
		private System.Nullable<int> _form_position;
		
		private string _form_name;
		
		private string _form_link;
		
		private System.Nullable<bool> _form_active;
		
		private System.Nullable<int> _module_id;
		
		private EntitySet<admin_AccessUserForm> _admin_AccessUserForms;
		
		private EntityRef<admin_Module> _admin_Module;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onform_idChanging(int value);
    partial void Onform_idChanged();
    partial void Onform_positionChanging(System.Nullable<int> value);
    partial void Onform_positionChanged();
    partial void Onform_nameChanging(string value);
    partial void Onform_nameChanged();
    partial void Onform_linkChanging(string value);
    partial void Onform_linkChanged();
    partial void Onform_activeChanging(System.Nullable<bool> value);
    partial void Onform_activeChanged();
    partial void Onmodule_idChanging(System.Nullable<int> value);
    partial void Onmodule_idChanged();
    #endregion
		
		public admin_Form()
		{
			this._admin_AccessUserForms = new EntitySet<admin_AccessUserForm>(new Action<admin_AccessUserForm>(this.attach_admin_AccessUserForms), new Action<admin_AccessUserForm>(this.detach_admin_AccessUserForms));
			this._admin_Module = default(EntityRef<admin_Module>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int form_id
		{
			get
			{
				return this._form_id;
			}
			set
			{
				if ((this._form_id != value))
				{
					this.Onform_idChanging(value);
					this.SendPropertyChanging();
					this._form_id = value;
					this.SendPropertyChanged("form_id");
					this.Onform_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_position", DbType="Int")]
		public System.Nullable<int> form_position
		{
			get
			{
				return this._form_position;
			}
			set
			{
				if ((this._form_position != value))
				{
					this.Onform_positionChanging(value);
					this.SendPropertyChanging();
					this._form_position = value;
					this.SendPropertyChanged("form_position");
					this.Onform_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_name", DbType="NVarChar(MAX)")]
		public string form_name
		{
			get
			{
				return this._form_name;
			}
			set
			{
				if ((this._form_name != value))
				{
					this.Onform_nameChanging(value);
					this.SendPropertyChanging();
					this._form_name = value;
					this.SendPropertyChanged("form_name");
					this.Onform_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_link", DbType="NVarChar(MAX)")]
		public string form_link
		{
			get
			{
				return this._form_link;
			}
			set
			{
				if ((this._form_link != value))
				{
					this.Onform_linkChanging(value);
					this.SendPropertyChanging();
					this._form_link = value;
					this.SendPropertyChanged("form_link");
					this.Onform_linkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_active", DbType="Bit")]
		public System.Nullable<bool> form_active
		{
			get
			{
				return this._form_active;
			}
			set
			{
				if ((this._form_active != value))
				{
					this.Onform_activeChanging(value);
					this.SendPropertyChanging();
					this._form_active = value;
					this.SendPropertyChanged("form_active");
					this.Onform_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_id", DbType="Int")]
		public System.Nullable<int> module_id
		{
			get
			{
				return this._module_id;
			}
			set
			{
				if ((this._module_id != value))
				{
					if (this._admin_Module.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmodule_idChanging(value);
					this.SendPropertyChanging();
					this._module_id = value;
					this.SendPropertyChanged("module_id");
					this.Onmodule_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Form_admin_AccessUserForm", Storage="_admin_AccessUserForms", ThisKey="form_id", OtherKey="form_id")]
		public EntitySet<admin_AccessUserForm> admin_AccessUserForms
		{
			get
			{
				return this._admin_AccessUserForms;
			}
			set
			{
				this._admin_AccessUserForms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Module_admin_Form", Storage="_admin_Module", ThisKey="module_id", OtherKey="module_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public admin_Module admin_Module
		{
			get
			{
				return this._admin_Module.Entity;
			}
			set
			{
				admin_Module previousValue = this._admin_Module.Entity;
				if (((previousValue != value) 
							|| (this._admin_Module.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._admin_Module.Entity = null;
						previousValue.admin_Forms.Remove(this);
					}
					this._admin_Module.Entity = value;
					if ((value != null))
					{
						value.admin_Forms.Add(this);
						this._module_id = value.module_id;
					}
					else
					{
						this._module_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("admin_Module");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admin_AccessUserForms(admin_AccessUserForm entity)
		{
			this.SendPropertyChanging();
			entity.admin_Form = this;
		}
		
		private void detach_admin_AccessUserForms(admin_AccessUserForm entity)
		{
			this.SendPropertyChanging();
			entity.admin_Form = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_GroupUser")]
	public partial class admin_GroupUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _groupuser_id;
		
		private string _groupuser_name;
		
		private System.Nullable<bool> _groupuser_active;
		
		private EntitySet<admin_AccessGroupUserForm> _admin_AccessGroupUserForms;
		
		private EntitySet<admin_AccessGroupUserModule> _admin_AccessGroupUserModules;
		
		private EntitySet<admin_User> _admin_Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongroupuser_idChanging(int value);
    partial void Ongroupuser_idChanged();
    partial void Ongroupuser_nameChanging(string value);
    partial void Ongroupuser_nameChanged();
    partial void Ongroupuser_activeChanging(System.Nullable<bool> value);
    partial void Ongroupuser_activeChanged();
    #endregion
		
		public admin_GroupUser()
		{
			this._admin_AccessGroupUserForms = new EntitySet<admin_AccessGroupUserForm>(new Action<admin_AccessGroupUserForm>(this.attach_admin_AccessGroupUserForms), new Action<admin_AccessGroupUserForm>(this.detach_admin_AccessGroupUserForms));
			this._admin_AccessGroupUserModules = new EntitySet<admin_AccessGroupUserModule>(new Action<admin_AccessGroupUserModule>(this.attach_admin_AccessGroupUserModules), new Action<admin_AccessGroupUserModule>(this.detach_admin_AccessGroupUserModules));
			this._admin_Users = new EntitySet<admin_User>(new Action<admin_User>(this.attach_admin_Users), new Action<admin_User>(this.detach_admin_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int groupuser_id
		{
			get
			{
				return this._groupuser_id;
			}
			set
			{
				if ((this._groupuser_id != value))
				{
					this.Ongroupuser_idChanging(value);
					this.SendPropertyChanging();
					this._groupuser_id = value;
					this.SendPropertyChanged("groupuser_id");
					this.Ongroupuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_name", DbType="NVarChar(MAX)")]
		public string groupuser_name
		{
			get
			{
				return this._groupuser_name;
			}
			set
			{
				if ((this._groupuser_name != value))
				{
					this.Ongroupuser_nameChanging(value);
					this.SendPropertyChanging();
					this._groupuser_name = value;
					this.SendPropertyChanged("groupuser_name");
					this.Ongroupuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_active", DbType="Bit")]
		public System.Nullable<bool> groupuser_active
		{
			get
			{
				return this._groupuser_active;
			}
			set
			{
				if ((this._groupuser_active != value))
				{
					this.Ongroupuser_activeChanging(value);
					this.SendPropertyChanging();
					this._groupuser_active = value;
					this.SendPropertyChanged("groupuser_active");
					this.Ongroupuser_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_GroupUser_admin_AccessGroupUserForm", Storage="_admin_AccessGroupUserForms", ThisKey="groupuser_id", OtherKey="groupuser_id")]
		public EntitySet<admin_AccessGroupUserForm> admin_AccessGroupUserForms
		{
			get
			{
				return this._admin_AccessGroupUserForms;
			}
			set
			{
				this._admin_AccessGroupUserForms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_GroupUser_admin_AccessGroupUserModule", Storage="_admin_AccessGroupUserModules", ThisKey="groupuser_id", OtherKey="groupuser_id")]
		public EntitySet<admin_AccessGroupUserModule> admin_AccessGroupUserModules
		{
			get
			{
				return this._admin_AccessGroupUserModules;
			}
			set
			{
				this._admin_AccessGroupUserModules.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_GroupUser_admin_User", Storage="_admin_Users", ThisKey="groupuser_id", OtherKey="groupuser_id")]
		public EntitySet<admin_User> admin_Users
		{
			get
			{
				return this._admin_Users;
			}
			set
			{
				this._admin_Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admin_AccessGroupUserForms(admin_AccessGroupUserForm entity)
		{
			this.SendPropertyChanging();
			entity.admin_GroupUser = this;
		}
		
		private void detach_admin_AccessGroupUserForms(admin_AccessGroupUserForm entity)
		{
			this.SendPropertyChanging();
			entity.admin_GroupUser = null;
		}
		
		private void attach_admin_AccessGroupUserModules(admin_AccessGroupUserModule entity)
		{
			this.SendPropertyChanging();
			entity.admin_GroupUser = this;
		}
		
		private void detach_admin_AccessGroupUserModules(admin_AccessGroupUserModule entity)
		{
			this.SendPropertyChanging();
			entity.admin_GroupUser = null;
		}
		
		private void attach_admin_Users(admin_User entity)
		{
			this.SendPropertyChanging();
			entity.admin_GroupUser = this;
		}
		
		private void detach_admin_Users(admin_User entity)
		{
			this.SendPropertyChanging();
			entity.admin_GroupUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_Module")]
	public partial class admin_Module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _module_id;
		
		private System.Nullable<int> _module_position;
		
		private string _module_name;
		
		private string _module_icon;
		
		private System.Nullable<bool> _module_active;
		
		private EntitySet<admin_AccessGroupUserModule> _admin_AccessGroupUserModules;
		
		private EntitySet<admin_Form> _admin_Forms;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmodule_idChanging(int value);
    partial void Onmodule_idChanged();
    partial void Onmodule_positionChanging(System.Nullable<int> value);
    partial void Onmodule_positionChanged();
    partial void Onmodule_nameChanging(string value);
    partial void Onmodule_nameChanged();
    partial void Onmodule_iconChanging(string value);
    partial void Onmodule_iconChanged();
    partial void Onmodule_activeChanging(System.Nullable<bool> value);
    partial void Onmodule_activeChanged();
    #endregion
		
		public admin_Module()
		{
			this._admin_AccessGroupUserModules = new EntitySet<admin_AccessGroupUserModule>(new Action<admin_AccessGroupUserModule>(this.attach_admin_AccessGroupUserModules), new Action<admin_AccessGroupUserModule>(this.detach_admin_AccessGroupUserModules));
			this._admin_Forms = new EntitySet<admin_Form>(new Action<admin_Form>(this.attach_admin_Forms), new Action<admin_Form>(this.detach_admin_Forms));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int module_id
		{
			get
			{
				return this._module_id;
			}
			set
			{
				if ((this._module_id != value))
				{
					this.Onmodule_idChanging(value);
					this.SendPropertyChanging();
					this._module_id = value;
					this.SendPropertyChanged("module_id");
					this.Onmodule_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_position", DbType="Int")]
		public System.Nullable<int> module_position
		{
			get
			{
				return this._module_position;
			}
			set
			{
				if ((this._module_position != value))
				{
					this.Onmodule_positionChanging(value);
					this.SendPropertyChanging();
					this._module_position = value;
					this.SendPropertyChanged("module_position");
					this.Onmodule_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_name", DbType="NVarChar(MAX)")]
		public string module_name
		{
			get
			{
				return this._module_name;
			}
			set
			{
				if ((this._module_name != value))
				{
					this.Onmodule_nameChanging(value);
					this.SendPropertyChanging();
					this._module_name = value;
					this.SendPropertyChanged("module_name");
					this.Onmodule_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_icon", DbType="NVarChar(MAX)")]
		public string module_icon
		{
			get
			{
				return this._module_icon;
			}
			set
			{
				if ((this._module_icon != value))
				{
					this.Onmodule_iconChanging(value);
					this.SendPropertyChanging();
					this._module_icon = value;
					this.SendPropertyChanged("module_icon");
					this.Onmodule_iconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_active", DbType="Bit")]
		public System.Nullable<bool> module_active
		{
			get
			{
				return this._module_active;
			}
			set
			{
				if ((this._module_active != value))
				{
					this.Onmodule_activeChanging(value);
					this.SendPropertyChanging();
					this._module_active = value;
					this.SendPropertyChanged("module_active");
					this.Onmodule_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Module_admin_AccessGroupUserModule", Storage="_admin_AccessGroupUserModules", ThisKey="module_id", OtherKey="module_id")]
		public EntitySet<admin_AccessGroupUserModule> admin_AccessGroupUserModules
		{
			get
			{
				return this._admin_AccessGroupUserModules;
			}
			set
			{
				this._admin_AccessGroupUserModules.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Module_admin_Form", Storage="_admin_Forms", ThisKey="module_id", OtherKey="module_id")]
		public EntitySet<admin_Form> admin_Forms
		{
			get
			{
				return this._admin_Forms;
			}
			set
			{
				this._admin_Forms.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admin_AccessGroupUserModules(admin_AccessGroupUserModule entity)
		{
			this.SendPropertyChanging();
			entity.admin_Module = this;
		}
		
		private void detach_admin_AccessGroupUserModules(admin_AccessGroupUserModule entity)
		{
			this.SendPropertyChanging();
			entity.admin_Module = null;
		}
		
		private void attach_admin_Forms(admin_Form entity)
		{
			this.SendPropertyChanging();
			entity.admin_Module = this;
		}
		
		private void detach_admin_Forms(admin_Form entity)
		{
			this.SendPropertyChanging();
			entity.admin_Module = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_User")]
	public partial class admin_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _username_id;
		
		private string _username_username;
		
		private string _username_password;
		
		private string _username_fullname;
		
		private System.Nullable<bool> _username_gender;
		
		private string _username_phone;
		
		private string _username_email;
		
		private System.Nullable<bool> _username_active;
		
		private System.Nullable<int> _groupuser_id;
		
		private EntitySet<admin_AccessUserForm> _admin_AccessUserForms;
		
		private EntityRef<admin_GroupUser> _admin_GroupUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusername_idChanging(int value);
    partial void Onusername_idChanged();
    partial void Onusername_usernameChanging(string value);
    partial void Onusername_usernameChanged();
    partial void Onusername_passwordChanging(string value);
    partial void Onusername_passwordChanged();
    partial void Onusername_fullnameChanging(string value);
    partial void Onusername_fullnameChanged();
    partial void Onusername_genderChanging(System.Nullable<bool> value);
    partial void Onusername_genderChanged();
    partial void Onusername_phoneChanging(string value);
    partial void Onusername_phoneChanged();
    partial void Onusername_emailChanging(string value);
    partial void Onusername_emailChanged();
    partial void Onusername_activeChanging(System.Nullable<bool> value);
    partial void Onusername_activeChanged();
    partial void Ongroupuser_idChanging(System.Nullable<int> value);
    partial void Ongroupuser_idChanged();
    #endregion
		
		public admin_User()
		{
			this._admin_AccessUserForms = new EntitySet<admin_AccessUserForm>(new Action<admin_AccessUserForm>(this.attach_admin_AccessUserForms), new Action<admin_AccessUserForm>(this.detach_admin_AccessUserForms));
			this._admin_GroupUser = default(EntityRef<admin_GroupUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int username_id
		{
			get
			{
				return this._username_id;
			}
			set
			{
				if ((this._username_id != value))
				{
					this.Onusername_idChanging(value);
					this.SendPropertyChanging();
					this._username_id = value;
					this.SendPropertyChanged("username_id");
					this.Onusername_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_username", DbType="NVarChar(MAX)")]
		public string username_username
		{
			get
			{
				return this._username_username;
			}
			set
			{
				if ((this._username_username != value))
				{
					this.Onusername_usernameChanging(value);
					this.SendPropertyChanging();
					this._username_username = value;
					this.SendPropertyChanged("username_username");
					this.Onusername_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_password", DbType="NVarChar(MAX)")]
		public string username_password
		{
			get
			{
				return this._username_password;
			}
			set
			{
				if ((this._username_password != value))
				{
					this.Onusername_passwordChanging(value);
					this.SendPropertyChanging();
					this._username_password = value;
					this.SendPropertyChanged("username_password");
					this.Onusername_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_fullname", DbType="NVarChar(MAX)")]
		public string username_fullname
		{
			get
			{
				return this._username_fullname;
			}
			set
			{
				if ((this._username_fullname != value))
				{
					this.Onusername_fullnameChanging(value);
					this.SendPropertyChanging();
					this._username_fullname = value;
					this.SendPropertyChanged("username_fullname");
					this.Onusername_fullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_gender", DbType="Bit")]
		public System.Nullable<bool> username_gender
		{
			get
			{
				return this._username_gender;
			}
			set
			{
				if ((this._username_gender != value))
				{
					this.Onusername_genderChanging(value);
					this.SendPropertyChanging();
					this._username_gender = value;
					this.SendPropertyChanged("username_gender");
					this.Onusername_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_phone", DbType="NVarChar(MAX)")]
		public string username_phone
		{
			get
			{
				return this._username_phone;
			}
			set
			{
				if ((this._username_phone != value))
				{
					this.Onusername_phoneChanging(value);
					this.SendPropertyChanging();
					this._username_phone = value;
					this.SendPropertyChanged("username_phone");
					this.Onusername_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_email", DbType="NVarChar(MAX)")]
		public string username_email
		{
			get
			{
				return this._username_email;
			}
			set
			{
				if ((this._username_email != value))
				{
					this.Onusername_emailChanging(value);
					this.SendPropertyChanging();
					this._username_email = value;
					this.SendPropertyChanged("username_email");
					this.Onusername_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_active", DbType="Bit")]
		public System.Nullable<bool> username_active
		{
			get
			{
				return this._username_active;
			}
			set
			{
				if ((this._username_active != value))
				{
					this.Onusername_activeChanging(value);
					this.SendPropertyChanging();
					this._username_active = value;
					this.SendPropertyChanged("username_active");
					this.Onusername_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_id", DbType="Int")]
		public System.Nullable<int> groupuser_id
		{
			get
			{
				return this._groupuser_id;
			}
			set
			{
				if ((this._groupuser_id != value))
				{
					if (this._admin_GroupUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongroupuser_idChanging(value);
					this.SendPropertyChanging();
					this._groupuser_id = value;
					this.SendPropertyChanged("groupuser_id");
					this.Ongroupuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_User_admin_AccessUserForm", Storage="_admin_AccessUserForms", ThisKey="username_id", OtherKey="username_id")]
		public EntitySet<admin_AccessUserForm> admin_AccessUserForms
		{
			get
			{
				return this._admin_AccessUserForms;
			}
			set
			{
				this._admin_AccessUserForms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_GroupUser_admin_User", Storage="_admin_GroupUser", ThisKey="groupuser_id", OtherKey="groupuser_id", IsForeignKey=true)]
		public admin_GroupUser admin_GroupUser
		{
			get
			{
				return this._admin_GroupUser.Entity;
			}
			set
			{
				admin_GroupUser previousValue = this._admin_GroupUser.Entity;
				if (((previousValue != value) 
							|| (this._admin_GroupUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._admin_GroupUser.Entity = null;
						previousValue.admin_Users.Remove(this);
					}
					this._admin_GroupUser.Entity = value;
					if ((value != null))
					{
						value.admin_Users.Add(this);
						this._groupuser_id = value.groupuser_id;
					}
					else
					{
						this._groupuser_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("admin_GroupUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_admin_AccessUserForms(admin_AccessUserForm entity)
		{
			this.SendPropertyChanging();
			entity.admin_User = this;
		}
		
		private void detach_admin_AccessUserForms(admin_AccessUserForm entity)
		{
			this.SendPropertyChanging();
			entity.admin_User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbHoaDon")]
	public partial class tbHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hoadon_id;
		
		private System.DateTime _hoadon_ngaytao;
		
		private string _hoadon_khachhang;
		
		private System.Nullable<int> _haodon_tongcong;
		
		private EntitySet<tbHoaDonChiTiet> _tbHoaDonChiTiets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhoadon_idChanging(int value);
    partial void Onhoadon_idChanged();
    partial void Onhoadon_ngaytaoChanging(System.DateTime value);
    partial void Onhoadon_ngaytaoChanged();
    partial void Onhoadon_khachhangChanging(string value);
    partial void Onhoadon_khachhangChanged();
    partial void Onhaodon_tongcongChanging(System.Nullable<int> value);
    partial void Onhaodon_tongcongChanged();
    #endregion
		
		public tbHoaDon()
		{
			this._tbHoaDonChiTiets = new EntitySet<tbHoaDonChiTiet>(new Action<tbHoaDonChiTiet>(this.attach_tbHoaDonChiTiets), new Action<tbHoaDonChiTiet>(this.detach_tbHoaDonChiTiets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hoadon_id
		{
			get
			{
				return this._hoadon_id;
			}
			set
			{
				if ((this._hoadon_id != value))
				{
					this.Onhoadon_idChanging(value);
					this.SendPropertyChanging();
					this._hoadon_id = value;
					this.SendPropertyChanged("hoadon_id");
					this.Onhoadon_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_ngaytao", DbType="Date NOT NULL")]
		public System.DateTime hoadon_ngaytao
		{
			get
			{
				return this._hoadon_ngaytao;
			}
			set
			{
				if ((this._hoadon_ngaytao != value))
				{
					this.Onhoadon_ngaytaoChanging(value);
					this.SendPropertyChanging();
					this._hoadon_ngaytao = value;
					this.SendPropertyChanged("hoadon_ngaytao");
					this.Onhoadon_ngaytaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_khachhang", DbType="VarChar(255)")]
		public string hoadon_khachhang
		{
			get
			{
				return this._hoadon_khachhang;
			}
			set
			{
				if ((this._hoadon_khachhang != value))
				{
					this.Onhoadon_khachhangChanging(value);
					this.SendPropertyChanging();
					this._hoadon_khachhang = value;
					this.SendPropertyChanged("hoadon_khachhang");
					this.Onhoadon_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haodon_tongcong", DbType="Int")]
		public System.Nullable<int> haodon_tongcong
		{
			get
			{
				return this._haodon_tongcong;
			}
			set
			{
				if ((this._haodon_tongcong != value))
				{
					this.Onhaodon_tongcongChanging(value);
					this.SendPropertyChanging();
					this._haodon_tongcong = value;
					this.SendPropertyChanged("haodon_tongcong");
					this.Onhaodon_tongcongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbHoaDon_tbHoaDonChiTiet", Storage="_tbHoaDonChiTiets", ThisKey="hoadon_id", OtherKey="hoadon_id")]
		public EntitySet<tbHoaDonChiTiet> tbHoaDonChiTiets
		{
			get
			{
				return this._tbHoaDonChiTiets;
			}
			set
			{
				this._tbHoaDonChiTiets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbHoaDonChiTiets(tbHoaDonChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbHoaDon = this;
		}
		
		private void detach_tbHoaDonChiTiets(tbHoaDonChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbHoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbHoaDonChiTiet")]
	public partial class tbHoaDonChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hdct_id;
		
		private System.Nullable<int> _hoadon_id;
		
		private System.Nullable<int> _sanpham_id;
		
		private System.Nullable<int> _hdct_gia;
		
		private EntityRef<tbHoaDon> _tbHoaDon;
		
		private EntityRef<tbSanPham> _tbSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhdct_idChanging(int value);
    partial void Onhdct_idChanged();
    partial void Onhoadon_idChanging(System.Nullable<int> value);
    partial void Onhoadon_idChanged();
    partial void Onsanpham_idChanging(System.Nullable<int> value);
    partial void Onsanpham_idChanged();
    partial void Onhdct_giaChanging(System.Nullable<int> value);
    partial void Onhdct_giaChanged();
    #endregion
		
		public tbHoaDonChiTiet()
		{
			this._tbHoaDon = default(EntityRef<tbHoaDon>);
			this._tbSanPham = default(EntityRef<tbSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hdct_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hdct_id
		{
			get
			{
				return this._hdct_id;
			}
			set
			{
				if ((this._hdct_id != value))
				{
					this.Onhdct_idChanging(value);
					this.SendPropertyChanging();
					this._hdct_id = value;
					this.SendPropertyChanged("hdct_id");
					this.Onhdct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_id", DbType="Int")]
		public System.Nullable<int> hoadon_id
		{
			get
			{
				return this._hoadon_id;
			}
			set
			{
				if ((this._hoadon_id != value))
				{
					if (this._tbHoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhoadon_idChanging(value);
					this.SendPropertyChanging();
					this._hoadon_id = value;
					this.SendPropertyChanged("hoadon_id");
					this.Onhoadon_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_id", DbType="Int")]
		public System.Nullable<int> sanpham_id
		{
			get
			{
				return this._sanpham_id;
			}
			set
			{
				if ((this._sanpham_id != value))
				{
					if (this._tbSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsanpham_idChanging(value);
					this.SendPropertyChanging();
					this._sanpham_id = value;
					this.SendPropertyChanged("sanpham_id");
					this.Onsanpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hdct_gia", DbType="Int")]
		public System.Nullable<int> hdct_gia
		{
			get
			{
				return this._hdct_gia;
			}
			set
			{
				if ((this._hdct_gia != value))
				{
					this.Onhdct_giaChanging(value);
					this.SendPropertyChanging();
					this._hdct_gia = value;
					this.SendPropertyChanged("hdct_gia");
					this.Onhdct_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbHoaDon_tbHoaDonChiTiet", Storage="_tbHoaDon", ThisKey="hoadon_id", OtherKey="hoadon_id", IsForeignKey=true)]
		public tbHoaDon tbHoaDon
		{
			get
			{
				return this._tbHoaDon.Entity;
			}
			set
			{
				tbHoaDon previousValue = this._tbHoaDon.Entity;
				if (((previousValue != value) 
							|| (this._tbHoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbHoaDon.Entity = null;
						previousValue.tbHoaDonChiTiets.Remove(this);
					}
					this._tbHoaDon.Entity = value;
					if ((value != null))
					{
						value.tbHoaDonChiTiets.Add(this);
						this._hoadon_id = value.hoadon_id;
					}
					else
					{
						this._hoadon_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbHoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSanPham_tbHoaDonChiTiet", Storage="_tbSanPham", ThisKey="sanpham_id", OtherKey="sanpham_id", IsForeignKey=true)]
		public tbSanPham tbSanPham
		{
			get
			{
				return this._tbSanPham.Entity;
			}
			set
			{
				tbSanPham previousValue = this._tbSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tbSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbSanPham.Entity = null;
						previousValue.tbHoaDonChiTiets.Remove(this);
					}
					this._tbSanPham.Entity = value;
					if ((value != null))
					{
						value.tbHoaDonChiTiets.Add(this);
						this._sanpham_id = value.sanpham_id;
					}
					else
					{
						this._sanpham_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbKho")]
	public partial class tbKho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kho_id;
		
		private string _kho_name;
		
		private string _kho_diachi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkho_idChanging(int value);
    partial void Onkho_idChanged();
    partial void Onkho_nameChanging(string value);
    partial void Onkho_nameChanged();
    partial void Onkho_diachiChanging(string value);
    partial void Onkho_diachiChanged();
    #endregion
		
		public tbKho()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kho_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kho_id
		{
			get
			{
				return this._kho_id;
			}
			set
			{
				if ((this._kho_id != value))
				{
					this.Onkho_idChanging(value);
					this.SendPropertyChanging();
					this._kho_id = value;
					this.SendPropertyChanged("kho_id");
					this.Onkho_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kho_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string kho_name
		{
			get
			{
				return this._kho_name;
			}
			set
			{
				if ((this._kho_name != value))
				{
					this.Onkho_nameChanging(value);
					this.SendPropertyChanging();
					this._kho_name = value;
					this.SendPropertyChanged("kho_name");
					this.Onkho_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kho_diachi", DbType="VarChar(255)")]
		public string kho_diachi
		{
			get
			{
				return this._kho_diachi;
			}
			set
			{
				if ((this._kho_diachi != value))
				{
					this.Onkho_diachiChanging(value);
					this.SendPropertyChanging();
					this._kho_diachi = value;
					this.SendPropertyChanged("kho_diachi");
					this.Onkho_diachiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSanPham")]
	public partial class tbSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sanpham_id;
		
		private string _sanpham_name;
		
		private string _sanpham_mota;
		
		private System.Nullable<int> _sanpham_gia;
		
		private EntitySet<tbHoaDonChiTiet> _tbHoaDonChiTiets;
		
		private EntitySet<tbSanPhamChiTiet> _tbSanPhamChiTiets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsanpham_idChanging(int value);
    partial void Onsanpham_idChanged();
    partial void Onsanpham_nameChanging(string value);
    partial void Onsanpham_nameChanged();
    partial void Onsanpham_motaChanging(string value);
    partial void Onsanpham_motaChanged();
    partial void Onsanpham_giaChanging(System.Nullable<int> value);
    partial void Onsanpham_giaChanged();
    #endregion
		
		public tbSanPham()
		{
			this._tbHoaDonChiTiets = new EntitySet<tbHoaDonChiTiet>(new Action<tbHoaDonChiTiet>(this.attach_tbHoaDonChiTiets), new Action<tbHoaDonChiTiet>(this.detach_tbHoaDonChiTiets));
			this._tbSanPhamChiTiets = new EntitySet<tbSanPhamChiTiet>(new Action<tbSanPhamChiTiet>(this.attach_tbSanPhamChiTiets), new Action<tbSanPhamChiTiet>(this.detach_tbSanPhamChiTiets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sanpham_id
		{
			get
			{
				return this._sanpham_id;
			}
			set
			{
				if ((this._sanpham_id != value))
				{
					this.Onsanpham_idChanging(value);
					this.SendPropertyChanging();
					this._sanpham_id = value;
					this.SendPropertyChanged("sanpham_id");
					this.Onsanpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string sanpham_name
		{
			get
			{
				return this._sanpham_name;
			}
			set
			{
				if ((this._sanpham_name != value))
				{
					this.Onsanpham_nameChanging(value);
					this.SendPropertyChanging();
					this._sanpham_name = value;
					this.SendPropertyChanged("sanpham_name");
					this.Onsanpham_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_mota", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string sanpham_mota
		{
			get
			{
				return this._sanpham_mota;
			}
			set
			{
				if ((this._sanpham_mota != value))
				{
					this.Onsanpham_motaChanging(value);
					this.SendPropertyChanging();
					this._sanpham_mota = value;
					this.SendPropertyChanged("sanpham_mota");
					this.Onsanpham_motaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_gia", DbType="Int")]
		public System.Nullable<int> sanpham_gia
		{
			get
			{
				return this._sanpham_gia;
			}
			set
			{
				if ((this._sanpham_gia != value))
				{
					this.Onsanpham_giaChanging(value);
					this.SendPropertyChanging();
					this._sanpham_gia = value;
					this.SendPropertyChanged("sanpham_gia");
					this.Onsanpham_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSanPham_tbHoaDonChiTiet", Storage="_tbHoaDonChiTiets", ThisKey="sanpham_id", OtherKey="sanpham_id")]
		public EntitySet<tbHoaDonChiTiet> tbHoaDonChiTiets
		{
			get
			{
				return this._tbHoaDonChiTiets;
			}
			set
			{
				this._tbHoaDonChiTiets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSanPham_tbSanPhamChiTiet", Storage="_tbSanPhamChiTiets", ThisKey="sanpham_id", OtherKey="sanpham_id")]
		public EntitySet<tbSanPhamChiTiet> tbSanPhamChiTiets
		{
			get
			{
				return this._tbSanPhamChiTiets;
			}
			set
			{
				this._tbSanPhamChiTiets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbHoaDonChiTiets(tbHoaDonChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbSanPham = this;
		}
		
		private void detach_tbHoaDonChiTiets(tbHoaDonChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbSanPham = null;
		}
		
		private void attach_tbSanPhamChiTiets(tbSanPhamChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbSanPham = this;
		}
		
		private void detach_tbSanPhamChiTiets(tbSanPhamChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.tbSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSanPhamChiTiet")]
	public partial class tbSanPhamChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _spct_id;
		
		private System.Nullable<int> _sanpham_id;
		
		private string _spct_motab;
		
		private EntityRef<tbSanPham> _tbSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onspct_idChanging(int value);
    partial void Onspct_idChanged();
    partial void Onsanpham_idChanging(System.Nullable<int> value);
    partial void Onsanpham_idChanged();
    partial void Onspct_motabChanging(string value);
    partial void Onspct_motabChanged();
    #endregion
		
		public tbSanPhamChiTiet()
		{
			this._tbSanPham = default(EntityRef<tbSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spct_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int spct_id
		{
			get
			{
				return this._spct_id;
			}
			set
			{
				if ((this._spct_id != value))
				{
					this.Onspct_idChanging(value);
					this.SendPropertyChanging();
					this._spct_id = value;
					this.SendPropertyChanged("spct_id");
					this.Onspct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_id", DbType="Int")]
		public System.Nullable<int> sanpham_id
		{
			get
			{
				return this._sanpham_id;
			}
			set
			{
				if ((this._sanpham_id != value))
				{
					if (this._tbSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsanpham_idChanging(value);
					this.SendPropertyChanging();
					this._sanpham_id = value;
					this.SendPropertyChanged("sanpham_id");
					this.Onsanpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spct_motab", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string spct_motab
		{
			get
			{
				return this._spct_motab;
			}
			set
			{
				if ((this._spct_motab != value))
				{
					this.Onspct_motabChanging(value);
					this.SendPropertyChanging();
					this._spct_motab = value;
					this.SendPropertyChanged("spct_motab");
					this.Onspct_motabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSanPham_tbSanPhamChiTiet", Storage="_tbSanPham", ThisKey="sanpham_id", OtherKey="sanpham_id", IsForeignKey=true)]
		public tbSanPham tbSanPham
		{
			get
			{
				return this._tbSanPham.Entity;
			}
			set
			{
				tbSanPham previousValue = this._tbSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tbSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbSanPham.Entity = null;
						previousValue.tbSanPhamChiTiets.Remove(this);
					}
					this._tbSanPham.Entity = value;
					if ((value != null))
					{
						value.tbSanPhamChiTiets.Add(this);
						this._sanpham_id = value.sanpham_id;
					}
					else
					{
						this._sanpham_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
