<?xml version="1.0" encoding="utf-8"?><Database Name="ql" Class="dbcsdlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-6MF64C4\SQLEXPRESS;Initial Catalog=ql;Integrated Security=True" SettingsObjectName="QuanLyTaiKhoan.Properties.Settings" SettingsPropertyName="qlConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin_AccessGroupUserForm" Member="admin_AccessGroupUserForms">
    <Type Name="admin_AccessGroupUserForm">
      <Column Name="guf_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="guf_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="groupuser_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="form_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_GroupUser_admin_AccessGroupUserForm" Member="admin_GroupUser" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_GroupUser" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tbSlides" Member="tbSlides">
    <Type Name="tbSlide">
      <Column Name="slide_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="slide_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slide_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="silde_title1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slide_link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slide_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="slide_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.admin_AccessGroupUserModule" Member="admin_AccessGroupUserModules">
    <Type Name="admin_AccessGroupUserModule">
      <Column Name="gum_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gum_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="groupuser_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="module_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_GroupUser_admin_AccessGroupUserModule" Member="admin_GroupUser" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_GroupUser" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="admin_Module_admin_AccessGroupUserModule" Member="admin_Module" ThisKey="module_id" OtherKey="module_id" Type="admin_Module" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.admin_AccessUserForm" Member="admin_AccessUserForms">
    <Type Name="admin_AccessUserForm">
      <Column Name="uf_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uf_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="username_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="form_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_Form_admin_AccessUserForm" Member="admin_Form" ThisKey="form_id" OtherKey="form_id" Type="admin_Form" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="admin_User_admin_AccessUserForm" Member="admin_User" ThisKey="username_id" OtherKey="username_id" Type="admin_User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.admin_Form" Member="admin_Forms">
    <Type Name="admin_Form">
      <Column Name="form_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="form_position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="form_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="form_link" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="form_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="module_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_Form_admin_AccessUserForm" Member="admin_AccessUserForms" ThisKey="form_id" OtherKey="form_id" Type="admin_AccessUserForm" />
      <Association Name="admin_Module_admin_Form" Member="admin_Module" ThisKey="module_id" OtherKey="module_id" Type="admin_Module" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.admin_GroupUser" Member="admin_GroupUsers">
    <Type Name="admin_GroupUser">
      <Column Name="groupuser_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="groupuser_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="groupuser_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="admin_GroupUser_admin_AccessGroupUserForm" Member="admin_AccessGroupUserForms" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_AccessGroupUserForm" />
      <Association Name="admin_GroupUser_admin_AccessGroupUserModule" Member="admin_AccessGroupUserModules" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_AccessGroupUserModule" />
      <Association Name="admin_GroupUser_admin_User" Member="admin_Users" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_User" />
    </Type>
  </Table>
  <Table Name="dbo.admin_Module" Member="admin_Modules">
    <Type Name="admin_Module">
      <Column Name="module_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="module_position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="module_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="module_icon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="module_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="admin_Module_admin_AccessGroupUserModule" Member="admin_AccessGroupUserModules" ThisKey="module_id" OtherKey="module_id" Type="admin_AccessGroupUserModule" />
      <Association Name="admin_Module_admin_Form" Member="admin_Forms" ThisKey="module_id" OtherKey="module_id" Type="admin_Form" />
    </Type>
  </Table>
  <Table Name="dbo.admin_User" Member="admin_Users">
    <Type Name="admin_User">
      <Column Name="username_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username_username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_fullname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="username_phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="groupuser_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="admin_User_admin_AccessUserForm" Member="admin_AccessUserForms" ThisKey="username_id" OtherKey="username_id" Type="admin_AccessUserForm" />
      <Association Name="admin_GroupUser_admin_User" Member="admin_GroupUser" ThisKey="groupuser_id" OtherKey="groupuser_id" Type="admin_GroupUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbChiTietDanhMuc" Member="tbChiTietDanhMucs">
    <Type Name="tbChiTietDanhMuc">
      <Column Name="ctdm_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="danhmuc_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="congty_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ctdm_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tbCongTy_tbChiTietDanhMuc" Member="tbCongTy" ThisKey="congty_id" OtherKey="congty_id" Type="tbCongTy" IsForeignKey="true" />
      <Association Name="tbDanhMuc_tbChiTietDanhMuc" Member="tbDanhMuc" ThisKey="danhmuc_id" OtherKey="danhmuc_id" Type="tbDanhMuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbCongTy" Member="tbCongTies">
    <Type Name="tbCongTy">
      <Column Name="congty_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="congty_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tbCongTy_tbChiTietDanhMuc" Member="tbChiTietDanhMucs" ThisKey="congty_id" OtherKey="congty_id" Type="tbChiTietDanhMuc" />
    </Type>
  </Table>
  <Table Name="dbo.tbCustomerAccount" Member="tbCustomerAccounts">
    <Type Name="tbCustomerAccount">
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customer_firstname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="customer_lastname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="customer_fullname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="customer_phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="customer_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="customer_address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="customer_user" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="customer_pass" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbDanhMuc" Member="tbDanhMucs">
    <Type Name="tbDanhMuc">
      <Column Name="danhmuc_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dahmuc_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tbDanhMuc_tbChiTietDanhMuc" Member="tbChiTietDanhMucs" ThisKey="danhmuc_id" OtherKey="danhmuc_id" Type="tbChiTietDanhMuc" />
    </Type>
  </Table>
  <Table Name="dbo.tbHoaDon" Member="tbHoaDons">
    <Type Name="tbHoaDon">
      <Column Name="hoadon_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="haodon_ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbKho" Member="tbKhos">
    <Type Name="tbKho">
      <Column Name="kho_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kho_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="kho_diachi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tbKho_tbSanPhanTrongKho" Member="tbSanPhanTrongKhos" ThisKey="kho_id" OtherKey="kho_id" Type="tbSanPhanTrongKho" />
    </Type>
  </Table>
  <Table Name="dbo.tbNewCate" Member="tbNewCates">
    <Type Name="tbNewCate">
      <Column Name="newcate_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="newcate_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="newcate_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="link_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbProduct" Member="tbProducts">
    <Type Name="tbProduct">
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_quantum" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_show" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_new" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="productcate_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title_web" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_keywords" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="h1_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="link_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_chungloai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thuonghieu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="meta_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_representative" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_cart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_price_new" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_price" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_promotions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="product_price_entry" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="product_soluong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbProductCate" Member="tbProductCates">
    <Type Name="tbProductCate">
      <Column Name="productcate_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="productcate_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="productcate_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="productcate_show" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="productgroup_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title_web" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_keywords" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="h1_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="link_seo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="productcate_parent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="productcate_content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="meta_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="active" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hidden" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbSanPham" Member="tbSanPhams">
    <Type Name="tbSanPham">
      <Column Name="sanpham_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sanpham_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tbSanPham_tbSanPhamChiTiet" Member="tbSanPhamChiTiets" ThisKey="sanpham_id" OtherKey="sanpham_id" Type="tbSanPhamChiTiet" />
    </Type>
  </Table>
  <Table Name="dbo.tbSanPhamChiTiet" Member="tbSanPhamChiTiets">
    <Type Name="tbSanPhamChiTiet">
      <Column Name="spct_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sanpham_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="spct_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="spct_gia" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="spct_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tbSanPhamChiTiet_tbSanPhanTrongKho" Member="tbSanPhanTrongKhos" ThisKey="spct_id" OtherKey="spct_id" Type="tbSanPhanTrongKho" />
      <Association Name="tbSanPham_tbSanPhamChiTiet" Member="tbSanPham" ThisKey="sanpham_id" OtherKey="sanpham_id" Type="tbSanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbSanPhanTrongKho" Member="tbSanPhanTrongKhos">
    <Type Name="tbSanPhanTrongKho">
      <Column Name="sptk_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="spct_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kho_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sptk_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="sptk_soluong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tbKho_tbSanPhanTrongKho" Member="tbKho" ThisKey="kho_id" OtherKey="kho_id" Type="tbKho" IsForeignKey="true" />
      <Association Name="tbSanPhamChiTiet_tbSanPhanTrongKho" Member="tbSanPhamChiTiet" ThisKey="spct_id" OtherKey="spct_id" Type="tbSanPhamChiTiet" IsForeignKey="true" />
    </Type>
  </Table>
</Database>